# Generated by Django 4.2.7 on 2024-01-18 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('logo', models.FileField(max_length=6000, upload_to='coin')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='allplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('minplan', models.CharField(max_length=50)),
                ('maxplan', models.CharField(max_length=50)),
                ('logo', models.FileField(max_length=6000, upload_to='coin')),
                ('uuid', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=50)),
                ('proof', models.FileField(max_length=6000, upload_to='coin')),
                ('approved', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.allcoin')),
            ],
        ),
        migrations.CreateModel(
            name='invested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=50)),
                ('Canreinvest', models.BooleanField(default=False)),
                ('howmantime', models.IntegerField(default=0)),
                ('amounttobeadd', models.IntegerField(default=0)),
                ('useronplan', models.ManyToManyField(blank=True, to='app.allplan')),
            ],
        ),
        migrations.CreateModel(
            name='refreedclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Userclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refercode', models.CharField(max_length=50)),
                ('howmanreferral', models.CharField(max_length=50)),
                ('Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.CharField(blank=True, max_length=50)),
                ('balance', models.IntegerField(default=0)),
                ('netincome', models.IntegerField(default=0)),
                ('depositincome', models.IntegerField(default=0)),
                ('limitedreinvest', models.CharField(default=3, max_length=50)),
                ('reinvest', models.BooleanField(default=False)),
                ('timesamp', models.DateTimeField()),
                ('deposit', models.ManyToManyField(blank=True, to='app.deposit')),
                ('invested', models.ManyToManyField(blank=True, to='app.invested')),
                ('refer', models.ManyToManyField(blank=True, to='app.refreedclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('withdraw', models.ManyToManyField(blank=True, to='app.withdraw')),
            ],
        ),
    ]
