# Generated by Django 5.0.4 on 2024-12-27 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='investmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=3000)),
                ('name', models.CharField(blank=True, max_length=3000)),
                ('min', models.CharField(blank=True, max_length=300000)),
                ('max', models.CharField(blank=True, max_length=300000)),
                ('forday', models.CharField(blank=True, max_length=300000)),
                ('percentage', models.CharField(blank=True, max_length=300000)),
                ('days', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(blank=True, default=1, max_length=3000)),
                ('name', models.CharField(blank=True, max_length=3000)),
                ('email', models.CharField(blank=True, default='nwabuezedavid333@gmail.com', max_length=3000)),
                ('logo', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=3000)),
                ('host', models.CharField(blank=True, default='http://127.0.0.1:8000', max_length=3000)),
                ('dis', models.CharField(blank=True, max_length=3000)),
                ('keyword', models.CharField(blank=True, max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('interest', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='transferedlg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=3000)),
                ('email', models.CharField(blank=True, max_length=4000)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('tyx', models.CharField(blank=True, default='credit', max_length=4000, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=3000)),
                ('name', models.CharField(blank=True, max_length=3000)),
                ('address', models.CharField(blank=True, max_length=300000)),
                ('image', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='withdrwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=3000)),
                ('username', models.CharField(blank=True, max_length=3000)),
                ('walletaddress', models.CharField(blank=True, max_length=3000)),
                ('name', models.CharField(blank=True, max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='invested',
            name='useronplan',
        ),
        migrations.RemoveField(
            model_name='userclient',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='userclient',
            name='invested',
        ),
        migrations.RemoveField(
            model_name='refreedclient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userclient',
            name='refer',
        ),
        migrations.RemoveField(
            model_name='userclient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userclient',
            name='withdraw',
        ),
        migrations.CreateModel(
            name='oninvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=4000)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=3000)),
                ('username', models.CharField(blank=True, max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True, max_length=3000)),
                ('verified', models.BooleanField(default=False)),
                ('walletpaidon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=40, null=True)),
                ('code', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('referralby', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referralamount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved', models.BooleanField(default=False)),
                ('canInvest', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deposite', models.ManyToManyField(blank=True, to='app.deposite')),
                ('investment', models.ManyToManyField(blank=True, to='app.oninvestment')),
                ('referral', models.ManyToManyField(blank=True, to='app.referral')),
                ('transferedlg', models.ManyToManyField(blank=True, to='app.transferedlg')),
                ('withdrwal', models.ManyToManyField(blank=True, to='app.withdrwal')),
            ],
        ),
        migrations.DeleteModel(
            name='allcoin',
        ),
        migrations.DeleteModel(
            name='allplan',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='invested',
        ),
        migrations.DeleteModel(
            name='refreedclient',
        ),
        migrations.DeleteModel(
            name='Userclient',
        ),
        migrations.DeleteModel(
            name='withdraw',
        ),
    ]
