# Generated by Django 5.0.4 on 2024-12-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_referral_reward_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='reward_amount',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
    ]
