# Generated by Django 5.0.4 on 2024-12-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_referral_reward_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='gender',
            new_name='zip',
        ),
    ]
