# Generated by Django 5.0.4 on 2024-12-29 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='walletpaidon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.wallet'),
        ),
    ]
