# Generated by Django 5.0.4 on 2025-02-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_oninvestment_coininvestment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oninvestment',
            old_name='coininvestment',
            new_name='coininvestmentx',
        ),
    ]
