# Generated by Django 5.0.4 on 2025-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_coininvestment_oninvestment_coininvestmentx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oninvestment',
            name='coininvestmentx',
            field=models.CharField(default='None', max_length=4000),
        ),
    ]
