# Generated by Django 5.0.4 on 2025-02-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_oninvestment_coininvestmentx'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='coinname',
            field=models.CharField(default='None', max_length=4000),
        ),
    ]
